// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llvgrketqgxonwxxylpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsdmdya2V0cWd4b253eHh5bHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMTk5ODgsImV4cCI6MjA3ODY5NTk4OH0.ycRXAbEjqGa77OCrNZjuUGLYobtDzV8p-zpdT0jbx_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});